with-expecter: true
dir: "mocks"
filename: "{{.InterfaceName | lower }}.generated.go"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
packages:
  github.com/0xPolygon/agglayer/etherman:
    config:
    interfaces:
      IEthereumClient:
        config:
          mockname: EthereumClientMock
          filename: etherman_client.generated.go
  github.com/0xPolygon/agglayer/silencer:
    config:
    interfaces:
      ISilencer:
        config:
          mockname: SilencerMock
          filename: silencer.generated.go
  github.com/0xPolygon/agglayer/types:
    config:
    interfaces:
      IDB:
        config:
          mockname: DBMock
          filename: db.generated.go
      IEtherman:
        config:
          mockname: EthermanMock
          filename: etherman.generated.go
      IEthTxManager:
        config:
          mockname: EthTxManagerMock
          filename: eth_tx_manager.generated.go
      IZkEVMClient:
        config:
          mockname: ZkEVMClientMock
          filename: zk_evm_client.generated.go
      IZkEVMClientPool:
        config:
          mockname: ZkEVMClientCacheMock
          filename: zk_evm_client_cache.generated.go
