name: 'Regression Tests - Agglayer'
description: 'Runs regression tests for Agglayer.'
author: 'Dan Moore'
inputs:
  zkevm_agglayer:
    description: 0xPolygon/agglayer (short commit hash or release tag)
    required: false
    default: 0.1.4
  zkevm_bridge_service:
    description: 0xPolygonHermez/zkevm-bridge-service (short commit hash or release tag)
    required: false
    default: v0.4.2
  zkevm_bridge_ui:
    description: 0xPolygonHermez/zkevm-bridge-ui (short commit hash or release tag)
    required: false
    default: '0006445'
  zkevm_dac:
    description: 0xPolygon/cdk-data-availability (short commit hash or release tag)
    required: false
    default: 0.0.7
  zkevm_node:
    description: 0xPolygon/cdk-validium-node (short commit hash or release tag)
    required: false
    default: 0.6.5-cdk
  bake_time:
    description: bake time (minutes)
    required: false
    default: 30
runs:
  using: 'docker'
  image: 'Dockerfile.action'
