version: '3.9'

services:
  interop-db:
    image: postgres:16.0-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: interop_user
      POSTGRES_PASSWORD: interop_password
      POSTGRES_DB: interop_db
    networks:
      - beethoven-localnet
    restart: always

  beethoven:
    image: beethoven:local-${ARCH}
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        ARCH: $ARCH
    command: [ 'run' ]
    depends_on:
      interop-db:
        condition: service_started
    ports:
      - '8444:8444'
    volumes:
      - ../data/pk:/pk
      - ../data/config:/config
    networks:
      - beethoven-localnet
    restart: always

networks:
  beethoven-localnet:
    driver: bridge
