name: "Build pipeline for agglayer-dev"
on:
  push:
    branches:
      - DEVOPS-2546/dev-deploy

env:
  PROJECT_ID: "prj-polygonlabs-shared-dev"
  GAR_LOCATION: "europe-west2"

  WIF_PROVIDER: "projects/595403903631/locations/global/workloadIdentityPools/build-pipeline-pool/providers/buildpipeline"
  WIF_SERVICE_ACCOUNT: "gcp-apps-build-pipeline-sa@prj-polygonlabs-shared-dev.iam.gserviceaccount.com"

  CRITICAL_COUNT: 5
  IMAGE_NAME: "europe-west2-docker.pkg.dev/prj-polygonlabs-shared-dev/polygonlabs-docker-dev/agglayer"

  ATTESTOR_PROJECT_ID: "prj-polygonlabs-shared-dev"
  KEY_RING: "gcp-apps-build-pipeline-ring"
  KEY: "gcp-apps-build-pipeline-key"
  ATTESTOR: "gcp-apps-build-pipeline-attestor"

jobs:
  build-pipeline:
    name: "Build pipeline for agglayer-dev"
    permissons:
      contents: "write"
      id-token: "write"

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - id: custom-action
        uses: 0xPolygon/pipelines@v3
        with:
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.WIF_SERVICE_ACCOUNT }}
          gar_location: ${{ env.GAR_LOCATION }}
          docker_image: ${{ env.IMAGE_NAME }}
          dockerfile_name: docker/Dockerfile
          dockerfile_path: .
          critical_count: ${{ env.CRITICAL_COUNT }}
          helm_values_path: 'helm-values/dev-values.yaml'
          attestor: ${{ env.ATTESTOR }}
          attestor_project: ${{ env.ATTESTOR_PROJECT_ID }}
          keyversion_project: ${{ env.ATTESTOR_PROJECT_ID }}
          keyversion_location: ${{ env.GAR_LOCATION }}
          keyversion_keyring: ${{ env.KEY_RING }}
          keyversion_key: ${{ env.KEY }}
