name: Build
on:
  workflow_dispatch: {}
  workflow_call: {}

jobs:
  lint:
    name: Execution
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.x

      - name: Install Packr2
        run: go install github.com/gobuffalo/packr/v2/packr2@v2.8.3

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: make build
