name: CI

on:
  workflow_dispatch: {}
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Linter Analysis
    uses: ./.github/workflows/lint.yml

  unit-tests:
    name: Unit Tests
    uses: ./.github/workflows/unit-test.yml

  sonar-scan:
    name: SonarCloud Scan
    uses: SonarSource/sonarcloud-github-action@master
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    needs: unit-tests

  e2e-tests:
    name: E2E Tests
    uses: ./.github/workflows/e2e.yml
