name: CI

on:
  workflow_dispatch: {}
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  unit-tests:
    uses: ./.github/workflows/unit-test.yml

  sonar-scan:
    uses: ./.github/workflows/sonar-scan.yml
    needs: unit-tests

  e2e-tests:
    uses: ./.github/workflows/e2e.yml
