name: E2E tests
on:
  workflow_dispatch:
  workflow_call:
    outputs:
      workflow_output:
        description: "E2E output"
        value: ${{ jobs.execution.outputs.e2e_output_failure }}

jobs:
  execution:
    name: "Execution"
    runs-on: ubuntu-latest
    env:
      CI_VERBOSE: true
    outputs:
      e2e_output_failure: ${{ steps.run_e2e_failure.outputs.test_output }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: make e2e-tests

      - name: Run tests failed
        if: failure()
        id: run_e2e_failure
        run: echo "test_output=false" >> $GITHUB_OUTPUT

      # TODO: Uncomment when we establish writing to log files in E2E framework
      # - name: Archive test logs
      #   if: always()
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: e2e-logs
      #     path: e2e-logs-*/
      #     retention-days: 30
