name: Regression Tests - Agglayer

on:
  pull_request:
    types: [opened, synchronize]  # Trigger on new PR's and existing ones with new commits
    branches:
      - main

jobs:
  deploy_devnet:
    runs-on: ubuntu-latest

    env:
      GITHUB_SHA: ${{ github.sha }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Run regression tests against custom user-specified images
        uses: 0xPolygon/kurtosis-cdk@v0.1.7
        with:
          zkevm_agglayer: ${{ env.GITHUB_SHA }}
