name: SonarCloud Scan

on:
  workflow_call:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: SonarCloud Scan
        if: ${{ env.HAVE_SONAR_TOKEN == 'true' }}
        uses: SonarSource/sonarcloud-github-action@master
        env:
          HAVE_SONAR_TOKEN: ${{ secrets.SONAR_TOKEN != '' }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
